### ISSUE TITLE
Parameter does not find parents

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn_common#141]
In this example returnn_common cannot find the parent of the variable layer:

```python
def test_variable():
  class _Net(nn.Module):

    def __init__(self, dim: nn.Dim):
      super().__init__()
      self.variable = nn.Parameter(shape=[dim])

    def __call__(self, x: nn.Tensor):
      return x + self.variable

  nn.reset_default_root_name_ctx()
  test_dim = nn.FeatureDim('test', 42)
  inputs = nn.get_extern_data(nn.Data('input', dim_tags=[test_dim]))
  net = _Net(test_dim)
  out = net(inputs)
  out.mark_as_default_output()
  config = nn.get_returnn_config().get_complete_py_code_str(net)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/hilmes/experiments/tts_new_sis/recipe/i6_private/users/hilmes/gauss_up.py", line 94, in test_variable
    config = nn.get_returnn_config().get_complete_py_code_str(net)
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/naming.py", line 657, in get_complete_py_code_str
    self.get_ext_net_dict_py_code_str(root_module=root_module, with_imports=False))
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/naming.py", line 688, in get_ext_net_dict_py_code_str
    net_dict = self.get_net_dict_raw_dict(root_module=root_module)
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/naming.py", line 710, in get_net_dict_raw_dict
    return NetDictBuilderCtx(root_module=root_module).make_net_dict_raw(self.name_ctx.make_net())
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/naming.py", line 897, in make_net_dict_raw
    layer_dict = nest.map_structure(_map_elem_resolve, layer_dict)
  File "/work/tools/asr/python/3.8.0_tf_2.3-v1-generic+cuda10.1/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 635, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/work/tools/asr/python/3.8.0_tf_2.3-v1-generic+cuda10.1/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 635, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/naming.py", line 885, in _map_elem_resolve
    return obj._get_name_in_ctx(ctx=net.name_ctx)
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/base.py", line 226, in _get_name_in_ctx
    self._assign_parent_name_ctx()
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/base.py", line 215, in _assign_parent_name_ctx
    assert self.name_ctx.parent, f"{self.parent_modules}"  # could not find parent
AssertionError: [(<_Net>, 'variable')]
```

Moving the Parameter into the `__call__` causes the same error.

**Comment by albertz** [comment]
Can you fix the traceback that you get the local vars? Why is that broken for you? How do you execute the test? When you add it to the testing suite and execute that, it should be correct.

**Comment by Atticus1806** [comment]
So I had a look at the other tests and realized that the `nn.scoped` decorator was missing. When adding it the test works. Is the decorator expected to be infront of every `__call__` of a Module, or is this only necessary in some cases? If so what are these cases? We could maybe then add them to the documentation or simply add the decorator to the README example.

**Comment by albertz** [comment]
No the nn.scoped should not have any influence on this.

**Comment by albertz** [comment]
Can you fix the traceback?


Benedikt Hilmes ***@***.***> schrieb am Fr., 29. Apr. 2022,
18:47:

**Comment by Atticus1806** [comment]
> No the nn.scoped should not have any influence on this.

Changing that line does fix the issue. So you say this is not intended to work like this? 

>How do you execute the test?

Python 3.8 Console, just importing it and running it. Derived it from a bigger Module I am currently working on implementing and when I saw that the variable was the problem of the Module I broke it down to this function.

**Comment by Atticus1806** [comment]
When running it from the test env this error comes up: 

```
╰─➤ python -m tests.test_nn_base test_variable                                                                                                                                                                 1 ↵
RETURNN: 1.20220429.093102+git.553ead2 /u/hilmes/experiments/tts_new_sis/recipe/returnn/__init__.py
2022-04-29 19:44:40.131789: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Installed libSegFault.so.
TensorFlow: 2.3.0
Test module: <module 'returnn_common.tests.test_nn_base' from '/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py'>
Running functions: ['test_variable']
--------------------------------------------------------------------------------

test_variable()
2022-04-29 19:44:42.361105: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2022-04-29 19:44:42.386203: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-04-29 19:44:42.386248: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (zink): /proc/driver/nvidia/version does not exist
2022-04-29 19:44:42.386757: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-29 19:44:42.392126: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3491995000 Hz
2022-04-29 19:44:42.392320: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4f349a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-04-29 19:44:42.392396: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
test
layer dummy_net/'add': [F|F'test'(42)] float32
Exception creating layer dummy_net/'add' of class CombineLayer with opts:
{'_name': 'add',
 '_network': <TFNetwork 'dummy_net' train>,
 'kind': 'add',
 'name': 'add',
 'network': <TFNetwork 'dummy_net' train>,
 'output': Data{'add_output', [F|F'test'(42)]},
 'sources': [<InternalLayer 'data:input' out_type=Data{[F|F'test'(42)]}>,
             <InternalLayer 'parameter' out_type=Data{[F|F'test'(42)]}>]}
EXCEPTION
Traceback (most recent call last):
  File "/work/tools/asr/python/3.8.0/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    line: return _run_code(code, main_globals, None,
                           "__main__", mod_spec)
    locals:
      _run_code = <global> <function _run_code at 0x7fc96fcdd430>
      code = <local> <code object <module> at 0x7fc96fc8e660, file "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py", line 1>
      main_globals = <local> {'__name__': '__main__', '__doc__': '\nTest the base nn functionality\n', '__package__': 'returnn_common.tests', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7fc96fcd4af0>, '__spec__': ModuleSpec(name='tests.test_nn_base', loader=<_frozen_importlib_external.SourceFileLoa..., len = 10
      mod_spec = <local> ModuleSpec(name='tests.test_nn_base', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc96fcd4af0>, origin='/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py')
  File "/work/tools/asr/python/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
    line: exec(code, run_globals)
    locals:
      exec = <builtin> <built-in function exec>
      code = <local> <code object <module> at 0x7fc96fc8e660, file "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py", line 1>
      run_globals = <local> {'__name__': '__main__', '__doc__': '\nTest the base nn functionality\n', '__package__': 'returnn_common.tests', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7fc96fcd4af0>, '__spec__': ModuleSpec(name='tests.test_nn_base', loader=<_frozen_importlib_external.SourceFileLoa..., len = 10
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py", line 7, in <module>
    line: from . import _setup_test_env  # noqa                                                                                                                                                            [95/389]
    locals:
      from = <not found>
      from.import = <not found>
      _setup_test_env = <not found>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/_setup_test_env.py", line 224, in <module>
    line: setup()
    locals:
      setup = <local> <function setup at 0x7fc96fc93430>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/_setup_test_env.py", line 127, in setup
    line: _main(main_mod_)
    locals:
      _main = <global> <function _main at 0x7fc96fc933a0>
      main_mod_ = <local> <module 'returnn_common.tests.test_nn_base' from '/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py'>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/_setup_test_env.py", line 203, in _main
    line: test()
    locals:
      test = <local> <function test_variable at 0x7fc92ee828b0>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py", line 457, in test_variable
    line: out = net(inputs, test_dim)
    locals:
      out = <not found>
      net = <local> <_Net>
      inputs = <local> <Tensor /'data:input' [F|F'test'(42)] <tf.Tensor: shape=(42,), dtype=float32, numpy=
                       array([ 1.5404702 ,  0.01790364,  0.4031491 , -1.035786  , -2.4868138 ,
                              -1.3182786 , -0.46188498,  1.6438249 ,  0.6654783 , -0.09698144,
                              -1.2607343 ,  1.6793586 , -0.13533416,  1.217893  , -2.614143...
      test_dim = <local> Dim{F'test'(42)}
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py", line 450, in test_variable.<locals>._Net.__call__
    line: return x + self.variable
    locals:
      x = <local> <Tensor /'data:input' [F|F'test'(42)] <tf.Tensor: shape=(42,), dtype=float32, numpy=
                  array([ 1.5404702 ,  0.01790364,  0.4031491 , -1.035786  , -2.4868138 ,
                         -1.3182786 , -0.46188498,  1.6438249 ,  0.6654783 , -0.09698144,
                         -1.2607343 ,  1.6793586 , -0.13533416,  1.217893  , -2.614143...
      self = <local> <_Net>
      self.variable = <local> <Parameter 'parameter' [F|F'test'(42)] <tf.Tensor: None> via 'variable'>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/base.py", line 379, in Tensor.__add__
    line: return _combine([self, nn.convert_to_tensor(other)], kind="add", name="add")
    locals:
      _combine = <local> <function _combine at 0x7fc92ee72ca0>
      self = <local> <Tensor /'data:input' [F|F'test'(42)] <tf.Tensor: shape=(42,), dtype=float32, numpy=
                     array([ 1.5404702 ,  0.01790364,  0.4031491 , -1.035786  , -2.4868138 ,
                            -1.3182786 , -0.46188498,  1.6438249 ,  0.6654783 , -0.09698144,
                            -1.2607343 ,  1.6793586 , -0.13533416,  1.217893  , -2.614143...
      nn = <global> <module 'returnn_common.nn' from '/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/__init__.py'>
      nn.convert_to_tensor = <global> <function convert_to_tensor at 0x7fc92ee7fc10>
      other = <local> <Parameter 'parameter' [F|F'test'(42)] <tf.Tensor: None> via 'variable'>
      kind = <not found>
      name = <not found>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/_generated_layers.py", line 1669, in _combine
    line: return nn.make_layer({
            'class': 'combine',
            'from': source,
           **args}, name=name or 'combine')
    locals:
      nn = <global> <module 'returnn_common.nn' from '/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/__init__.py'>
      nn.make_layer = <global> <function make_layer at 0x7fc92ee87280>
      source = <local> [<Tensor /'data:input' [F|F'test'(42)] <tf.Tensor: shape=(42,), dtype=float32, numpy=
                       array([ 1.5404702 ,  0.01790364,  0.4031491 , -1.035786  , -2.4868138 ,
                              -1.3182786 , -0.46188498,  1.6438249 ,  0.6654783 , -0.09698144,
                              -1.2607343 ,  1.6793586 , -0.13533416,  1.217893  , -2.61414...
      args = <local> {'kind': 'add'}
      name = <local> 'add'
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/base.py", line 664, in make_layer
    line: layer = Tensor(
            layer_dict=layer_dict, name_ctx=name_ctx,
            data=predefined_out_data)
    locals:
      layer = <not found>
      Tensor = <global> <class 'returnn_common.nn.base.Tensor'>
      layer_dict = <local> {'class': 'combine', 'from': [<Tensor /'data:input' [F|F'test'(42)] <tf.Tensor: shape=(42,), dtype=float32, numpy=
                           array([ 1.5404702 ,  0.01790364,  0.4031491 , -1.035786  , -2.4868138 ,
                                  -1.3182786 , -0.46188498,  1.6438249 ,  0.6654783 , -0.09698144,
                                  -1.2607343 ,  1.6793586 , -0.13...
      name_ctx = <local> !AttributeError: 'Tensor' object has no attribute 'data'
      data = <not found>
      predefined_out_data = <local> None
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/base.py", line 113, in Tensor.__init__
    line: data = _data_from_layer_dict(layer_dict, tensor=self)
    locals:
      data = <local> None
      _data_from_layer_dict = <global> <function _data_from_layer_dict at 0x7fc92ee9d670>
      layer_dict = <local> {'class': 'combine', 'from': [<Tensor /'data:input' [F|F'test'(42)] <tf.Tensor: shape=(42,), dtype=float32, numpy=
                           array([ 1.5404702 ,  0.01790364,  0.4031491 , -1.035786  , -2.4868138 ,
                                  -1.3182786 , -0.46188498,  1.6438249 ,  0.6654783 , -0.09698144,
                                  -1.2607343 ,  1.6793586 , -0.13...
      tensor = <not found>
      self = <local> <Tensor /'add' uninitialized>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/base.py", line 850, in _data_from_layer_dict
    line: layer = net.construct_layer(net_dict=net_dict, name=out_name, add_layer=_add_layer)
    locals:
      layer = <not found>
      net = <local> <TFNetwork 'dummy_net' train>
      net.construct_layer = <local> <bound method TFNetwork.construct_layer of <TFNetwork 'dummy_net' train>>
      net_dict = <local> {'add': {'class': 'combine', 'from': ['data:input', 'parameter'], 'kind': 'add'}}
      name = <not found>
      out_name = <local> 'add'
      add_layer = <not found>
      _add_layer = <local> None
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/network.py", line 961, in TFNetwork.construct_layer
    line: return add_layer(name=name_with_prefix, layer_class=layer_class, **layer_desc)
    locals:
      add_layer = <local> <bound method TFNetwork.add_layer of <TFNetwork 'dummy_net' train>>
      name = <local> 'add'
      name_with_prefix = <local> 'add'
      layer_class = <local> <class 'returnn.tf.layers.basic.CombineLayer'>
      layer_desc = <local> {'kind': 'add', '_network': <TFNetwork 'dummy_net' train>, '_name': 'add', 'sources': [<InternalLayer 'data:input' out_type=Data{[F|F'test'(42)]}>, <InternalLayer 'parameter' out_type=Data{[F|F'test'(42)]}>]}
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/network.py", line 1123, in TFNetwork.add_layer
    line: layer = self._create_layer(name=name, layer_class=layer_class, **layer_desc)
    locals:
      layer = <not found>
      self = <local> <TFNetwork 'dummy_net' train>
      self._create_layer = <local> <bound method TFNetwork._create_layer of <TFNetwork 'dummy_net' train>>
      name = <local> 'add'
      layer_class = <local> <class 'returnn.tf.layers.basic.CombineLayer'>
      layer_desc = <local> {'kind': 'add', '_network': <TFNetwork 'dummy_net' train>, '_name': 'add', 'sources': [<InternalLayer 'data:input' out_type=Data{[F|F'test'(42)]}>, <InternalLayer 'parameter' out_type=Data{[F|F'test'(42)]}>]}
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/network.py", line 1037, in TFNetwork._create_layer
    line: layer = layer_class(**layer_desc)
    locals:
      layer = <not found>
      layer_class = <local> <class 'returnn.tf.layers.basic.CombineLayer'>
      layer_desc = <local> {'kind': 'add', '_network': <TFNetwork 'dummy_net' train>, '_name': 'add', 'sources': [<InternalLayer 'data:input' out_type=Data{[F|F'test'(42)]}>, <InternalLayer 'parameter' out_type=Data{[F|F'test'(42)]}>], 'name': 'add', 'network': <TFNetwork 'dummy_net' train>, 'output': Data{'add_output', [F..., len = 7
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/layers/basic.py", line 7416, in CombineLayer.__init__
    line: x = op(sources)
    locals:
      x = <not found>
      op = <local> <bound method CombineLayer._op_kind_add of <CombineLayer 'add' out_type=Data{[F|F'test'(42)]}>>
      sources = <local> [<InternalLayer 'data:input' out_type=Data{[F|F'test'(42)]}>, <InternalLayer 'parameter' out_type=Data{[F|F'test'(42)]}>]
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/layers/basic.py", line 7521, in CombineLayer._op_kind_add
    line: return self._op_dense_fn(sources, tf.add, self.output)
    locals:
      self = <local> <CombineLayer 'add' out_type=Data{[F|F'test'(42)]}>
      self._op_dense_fn = <local> <function CombineLayer._op_dense_fn at 0x7fc92ef86f70>
      sources = <local> [<InternalLayer 'data:input' out_type=Data{[F|F'test'(42)]}>, <InternalLayer 'parameter' out_type=Data{[F|F'test'(42)]}>]
      tf = <global> <module 'tensorflow' from '/work/tools/asr/python/3.8.0_tf_2.3-v1-generic+cuda10.1/lib/python3.8/site-packages/tensorflow/__init__.py'>
      tf.add = <global> <function add at 0x7fc9426370d0>
      self.output = <local> Data{'add_output', [F|F'test'(42)]}
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/layers/basic.py", line 7512, in CombineLayer._op_dense_fn
    line: assert x2 is not None, "source.output missing placeholder? %r" % source
    locals:
      x2 = <local> None
      source = <local> <InternalLayer 'parameter' out_type=Data{[F|F'test'(42)]}>
AssertionError: source.output missing placeholder? <InternalLayer 'parameter' out_type=Data{[F|F'test'(42)]}>
```

**Comment by albertz** [comment]
I just notice, this is a different error now?

Also, it seems you have enabled eager mode here? Why? Disable that for now here. This looks like a separate (unrelated) error.

**Comment by Atticus1806** [comment]
Oh still had that on...

lets try this again: 
```python
2022-04-29 20:30:41.409319: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
EXCEPTION
Traceback (most recent call last):
  File "/work/tools/asr/python/3.8.0/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    line: return _run_code(code, main_globals, None,
                           "__main__", mod_spec)
    locals:
      _run_code = <global> <function _run_code at 0x7f015f9a0430>
      code = <local> <code object <module> at 0x7f015f97f5b0, file "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py", line 1>
      main_globals = <local> {'__name__': '__main__', '__doc__': '\nTest the base nn functionality\n', '__package__': 'returnn_common.tests', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7f015f997af0>, '__spec__': ModuleSpec(name='tests.test_nn_base', loader=<_frozen_importlib_external.SourceFileLoa..., len = 10
      mod_spec = <local> ModuleSpec(name='tests.test_nn_base', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f015f997af0>, origin='/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py')
  File "/work/tools/asr/python/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
    line: exec(code, run_globals)
    locals:
      exec = <builtin> <built-in function exec>
      code = <local> <code object <module> at 0x7f015f97f5b0, file "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py", line 1>
      run_globals = <local> {'__name__': '__main__', '__doc__': '\nTest the base nn functionality\n', '__package__': 'returnn_common.tests', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7f015f997af0>, '__spec__': ModuleSpec(name='tests.test_nn_base', loader=<_frozen_importlib_external.SourceFileLoa..., len = 10
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py", line 7, in <module>
    line: from . import _setup_test_env  # noqa
    locals:
      from = <not found>
      from.import = <not found>
      _setup_test_env = <not found>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/_setup_test_env.py", line 224, in <module>
    line: setup()
    locals:
      setup = <local> <function setup at 0x7f015f96b4c0>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/_setup_test_env.py", line 127, in setup
    line: _main(main_mod_)
    locals:
      _main = <global> <function _main at 0x7f015f96b430>
      main_mod_ = <local> <module 'returnn_common.tests.test_nn_base' from '/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py'>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/_setup_test_env.py", line 203, in _main
    line: test()
    locals:
      test = <local> <function test_variable at 0x7f011eb458b0>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/tests/test_nn_base.py", line 457, in test_variable
    line: config = nn.get_returnn_config().get_complete_py_code_str(net)
    locals:
      config = <not found>
      nn = <global> <module 'returnn_common.nn' from '/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/__init__.py'>
      nn.get_returnn_config = <global> <function get_returnn_config at 0x7f011eb61790>
      get_complete_py_code_str = <not found>
      net = <local> <_Net>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/naming.py", line 657, in ReturnnConfigSerializer.get_complete_py_code_str
    line: return (
            self.get_base_extern_data_py_code_str() +
            self.get_ext_net_dict_py_code_str(root_module=root_module, with_imports=False))
    locals:
      self = <local> <returnn_common.nn.naming.ReturnnConfigSerializer object at 0x7f011ea963d0>
      self.get_base_extern_data_py_code_str = <local> <bound method ReturnnConfigSerializer.get_base_extern_data_py_code_str of <returnn_common.nn.naming.ReturnnConfigSerializer object at 0x7f011ea963d0>>
      self.get_ext_net_dict_py_code_str = <local> <bound method ReturnnConfigSerializer.get_ext_net_dict_py_code_str of <returnn_common.nn.naming.ReturnnConfigSerializer object at 0x7f011ea963d0>>
      root_module = <local> <_Net>
      with_imports = <not found>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/naming.py", line 688, in ReturnnConfigSerializer.get_ext_net_dict_py_code_str
    line: net_dict = self.get_net_dict_raw_dict(root_module=root_module)
    locals:
      net_dict = <not found>
      self = <local> <returnn_common.nn.naming.ReturnnConfigSerializer object at 0x7f011ea963d0>
      self.get_net_dict_raw_dict = <local> <bound method ReturnnConfigSerializer.get_net_dict_raw_dict of <returnn_common.nn.naming.ReturnnConfigSerializer object at 0x7f011ea963d0>>
      root_module = <local> <_Net>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/naming.py", line 710, in ReturnnConfigSerializer.get_net_dict_raw_dict
    line: return NetDictBuilderCtx(root_module=root_module).make_net_dict_raw(self.name_ctx.make_net())
    locals:
      NetDictBuilderCtx = <global> <class 'returnn_common.nn.naming.NetDictBuilderCtx'>
      root_module = <local> <_Net>
      make_net_dict_raw = <not found>
      self = <local> <returnn_common.nn.naming.ReturnnConfigSerializer object at 0x7f011ea963d0>
      self.name_ctx = <local> <NameCtx />
      self.name_ctx.make_net = <local> <bound method NameCtx.make_net of <NameCtx />>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/naming.py", line 897, in NetDictBuilderCtx.make_net_dict_raw
    line: layer_dict = nest.map_structure(_map_elem_resolve, layer_dict)
    locals:
      layer_dict = <local> {'class': 'combine', 'from': [<Tensor /'data:input' [F|F'test'(42)]>, <Parameter 'parameter' [F|F'test'(42)] via 'variable'>], 'kind': 'add', 'out_shape': {Dim{F'test'(42)}}}
      nest = <global> <module 'tensorflow.python.util.nest' from '/work/tools/asr/python/3.8.0_tf_2.3-v1-generic+cuda10.1/lib/python3.8/site-packages/tensorflow/python/util/nest.py'>
      nest.map_structure = <global> <function map_structure at 0x7f01338a20d0>
      _map_elem_resolve = <local> <function NetDictBuilderCtx.make_net_dict_raw.<locals>._map_elem_resolve at 0x7f011e18ab80>
  File "/work/tools/asr/python/3.8.0_tf_2.3-v1-generic+cuda10.1/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 635, in map_structure
    line: structure[0], [func(*x) for x in entries],
    locals:
      structure = <local> ({'class': 'combine', 'from': [<Tensor /'data:input' [F|F'test'(42)]>, <Parameter 'parameter' [F|F'test'(42)] via 'variable'>], 'kind': 'add', 'out_shape': {Dim{F'test'(42)}}},)
      func = <local> <function NetDictBuilderCtx.make_net_dict_raw.<locals>._map_elem_resolve at 0x7f011e18ab80>
      x = <not found>
      entries = <local> <zip object at 0x7f011eaad7c0>
  File "/work/tools/asr/python/3.8.0_tf_2.3-v1-generic+cuda10.1/lib/python3.8/site-packages/tensorflow/python/util/nest.py", line 635, in <listcomp>
    line: structure[0], [func(*x) for x in entries],
    locals:
      structure = <not found>
      func = <local> <function NetDictBuilderCtx.make_net_dict_raw.<locals>._map_elem_resolve at 0x7f011e18ab80>
      x = <local> (<Parameter 'parameter' [F|F'test'(42)] via 'variable'>,)
      entries = <not found>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/naming.py", line 885, in NetDictBuilderCtx.make_net_dict_raw.<locals>._map_elem_resolve
    line: return obj._get_name_in_ctx(ctx=net.name_ctx)
    locals:
      obj = <local> <Parameter 'parameter' [F|F'test'(42)] via 'variable'>
      obj._get_name_in_ctx = <local> <bound method Tensor._get_name_in_ctx of <Parameter 'parameter' [F|F'test'(42)] via 'variable'>>
      ctx = <not found>
      net = <local> Net<NameCtx />
      net.name_ctx = <local> <NameCtx />
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/base.py", line 225, in Tensor._get_name_in_ctx
    line: self._assign_parent_name_ctx()
    locals:
      self = <local> <Parameter 'parameter' [F|F'test'(42)] via 'variable'>
      self._assign_parent_name_ctx = <local> <bound method Tensor._assign_parent_name_ctx of <Parameter 'parameter' [F|F'test'(42)] via 'variable'>>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn_common/nn/base.py", line 214, in Tensor._assign_parent_name_ctx
    line: assert self.name_ctx.parent, f"{self.parent_modules}"  # could not find parent
    locals:
      self = <local> <Parameter 'parameter' [F|F'test'(42)] via 'variable'>
      self.name_ctx = <local> <NameCtx 'parameter' [F|F'test'(42)]>
      self.name_ctx.parent = <local> None
AssertionError: [(<_Net>, 'variable')]
```
