### ISSUE TITLE
No Gradient for nn.random_normal

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn_common#198]
Extending the test from the issue yesterday with `train_epoch` gives an error for a missing gradient. 
From my understanding while propagating through the operation itself is not possible, but wrt. other components like when used in a sum is possible.
Or should this be set by the user manually? If so how would the user do this? 

```
EXCEPTION
Traceback (most recent call last):
  File "/u/hilmes/env/new_env/lib/python3.8/site-packages/tensorflow/python/ops/gradients_util.py", line 607, in _GradientsHelper
    line: grad_fn = ops.get_gradient_function(op)
    locals:
      grad_fn = <local> None
      ops = <global> <module 'tensorflow.python.framework.ops' from '/u/hilmes/env/new_env/lib/python3.8/site-packages/tensorflow/python/framework/ops.py'>
      ops.get_gradient_function = <global> <function get_gradient_function at 0x7f74c1e46ca0>
      op = <local> <tf.Operation 'random/random/stateful_normal/StatefulStandardNormalV2' type=StatefulStandardNormalV2>
  File "/u/hilmes/env/new_env/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2655, in get_gradient_function
    line: return _gradient_registry.lookup(op_type)
    locals:
      _gradient_registry = <global> <tensorflow.python.framework.registry.Registry object at 0x7f74c1e3cf70>
      _gradient_registry.lookup = <global> <bound method Registry.lookup of <tensorflow.python.framework.registry.Registry object at 0x7f74c1e3cf70>>
      op_type = <local> 'StatefulStandardNormalV2', len = 24
  File "/u/hilmes/env/new_env/lib/python3.8/site-packages/tensorflow/python/framework/registry.py", line 96, in Registry.lookup
    line: raise LookupError(
              "%s registry has no entry for: %s" % (self._name, name))
    locals:
      LookupError = <builtin> <class 'LookupError'>
      self = <local> <tensorflow.python.framework.registry.Registry object at 0x7f74c1e3cf70>
      self._name = <local> 'gradient', len = 8
      name = <local> 'StatefulStandardNormalV2', len = 24
LookupError: gradient registry has no entry for: StatefulStandardNormalV2

During handling of the above exception, another exception occurred:

EXCEPTION
Traceback (most recent call last):
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/engine.py", line 619, in Runner.run
    line: fetches_dict = self._get_fetches_dict()
    locals:
      fetches_dict = <local> None
      self = <local> <returnn.tf.engine.Runner object at 0x7f74ac205610>
      self._get_fetches_dict = <local> <bound method Runner._get_fetches_dict of <returnn.tf.engine.Runner object at 0x7f74ac205610>>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/engine.py", line 148, in Runner._get_fetches_dict
    line: optim_op = self.engine.updater.get_optim_op(callback_on_new=callback_on_new)
    locals:
      optim_op = <local> None
      self = <local> <returnn.tf.engine.Runner object at 0x7f74ac205610>
      self.engine = <local> <returnn.tf.engine.Engine object at 0x7f74ad5ba1f0>
      self.engine.updater = <local> <returnn.tf.updater.Updater object at 0x7f74ad5ba9d0>
      self.engine.updater.get_optim_op = <local> <bound method Updater.get_optim_op of <returnn.tf.updater.Updater object at 0x7f74ad5ba9d0>>
      callback_on_new = <local> <function Runner._get_fetches_dict.<locals>.callback_on_new at 0x7f74ac2aad30>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/updater.py", line 388, in Updater.get_optim_op
    line: self.create_optim_op()
    locals:
      self = <local> <returnn.tf.updater.Updater object at 0x7f74ad5ba9d0>
      self.create_optim_op = <local> <bound method Updater.create_optim_op of <returnn.tf.updater.Updater object at 0x7f74ad5ba9d0>>
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/updater.py", line 277, in Updater.create_optim_op
    line: apply_grads = self.get_apply_grads_op(self.loss, trainable_vars_for_gradients)
    locals:
      apply_grads = <not found>
      self = <local> <returnn.tf.updater.Updater object at 0x7f74ad5ba9d0>
      self.get_apply_grads_op = <local> <bound method Updater.get_apply_grads_op of <returnn.tf.updater.Updater object at 0x7f74ad5ba9d0>>
      self.loss = <local> <tf.Tensor 'objective/loss/loss/Sum:0' shape=() dtype=float32>
      trainable_vars_for_gradients = <local> [<tf.Variable 'random/state_var0/param:0' shape=(3,) dtype=int64>]
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/updater.py", line 874, in Updater.get_apply_grads_op
    line: grads_and_vars = self._compute_gradients(loss, var_list=var_list)
    locals:
      grads_and_vars = <not found>
      self = <local> <returnn.tf.updater.Updater object at 0x7f74ad5ba9d0>
      self._compute_gradients = <local> <bound method Updater._compute_gradients of <returnn.tf.updater.Updater object at 0x7f74ad5ba9d0>>
      loss = <local> <tf.Tensor 'objective/loss/loss/Sum:0' shape=() dtype=float32>
      var_list = <local> [<tf.Variable 'random/state_var0/param:0' shape=(3,) dtype=int64>]
  File "/u/hilmes/experiments/tts_new_sis/recipe/returnn/tf/updater.py", line 579, in Updater._compute_gradients
    line: return default_opt.compute_gradients(loss=loss, var_list=var_list, aggregation_method=aggregation_method)
    locals:
      default_opt = <local> <tensorflow.python.training.gradient_descent.GradientDescentOptimizer object at 0x7f74ac1bdfd0>
      default_opt.compute_gradients = <local> <bound method Optimizer.compute_gradients of <tensorflow.python.training.gradient_descent.GradientDescentOptimizer object at 0x7f74ac1bdfd0>>
      loss = <local> <tf.Tensor 'objective/loss/loss/Sum:0' shape=() dtype=float32>
      var_list = <local> [<tf.Variable 'random/state_var0/param:0' shape=(3,) dtype=int64>]
      aggregation_method = <local> 2
  File "/u/hilmes/env/new_env/lib/python3.8/site-packages/tensorflow/python/training/optimizer.py", line 508, in Optimizer.compute_gradients
    line: grads = gradients.gradients(
              loss, var_refs, grad_ys=grad_loss,
              gate_gradients=(gate_gradients == Optimizer.GATE_OP),
              aggregation_method=aggregation_method,
              colocate_gradients_with_ops=colocate_gradients_with_ops)
    locals:
      grads = <not found>
      gradients = <global> <module 'tensorflow.python.ops.gradients' from '/u/hilmes/env/new_env/lib/python3.8/site-packages/tensorflow/python/ops/gradients.py'>
      gradients.gradients = <global> <function gradients at 0x7f74bd7b3940>
      loss = <local> <tf.Tensor 'objective/loss/loss/Sum:0' shape=() dtype=float32>
      var_refs = <local> [<tf.Variable 'random/state_var0/param:0' shape=(3,) dtype=int64>]
      grad_ys = <not found>
      grad_loss = <local> None
      gate_gradients = <local> 1
      Optimizer = <global> <class 'tensorflow.python.training.optimizer.Optimizer'>
      Optimizer.GATE_OP = <global> 1
      aggregation_method = <local> 2
      colocate_gradients_with_ops = <local> False
  File "/u/hilmes/env/new_env/lib/python3.8/site-packages/tensorflow/python/ops/gradients_impl.py", line 169, in gradients
    line: return gradients_util._GradientsHelper(
              ys, xs, grad_ys, name, colocate_gradients_with_ops,
              gate_gradients, aggregation_method, stop_gradients,
              unconnected_gradients)
    locals:
      gradients_util = <global> <module 'tensorflow.python.ops.gradients_util' from '/u/hilmes/env/new_env/lib/python3.8/site-packages/tensorflow/python/ops/gradients_util.py'>
      gradients_util._GradientsHelper = <global> <function _GradientsHelper at 0x7f74bf6690d0>
      ys = <local> <tf.Tensor 'objective/loss/loss/Sum:0' shape=() dtype=float32>
      xs = <local> [<tf.Variable 'random/state_var0/param:0' shape=(3,) dtype=int64>]
      grad_ys = <local> None
      name = <local> 'gradients', len = 9
      colocate_gradients_with_ops = <local> False
      gate_gradients = <local> True
      aggregation_method = <local> 2
      stop_gradients = <local> None
      unconnected_gradients = <local> <UnconnectedGradients.NONE: 'none'>
  File "/u/hilmes/env/new_env/lib/python3.8/site-packages/tensorflow/python/ops/gradients_util.py", line 621, in _GradientsHelper
    line: raise LookupError(
              "No gradient defined for operation '%s' (op type: %s)" %
              (op.name, op.type))
    locals:
      LookupError = <builtin> <class 'LookupError'>
      op = <local> <tf.Operation 'random/random/stateful_normal/StatefulStandardNormalV2' type=StatefulStandardNormalV2>
      op.name = <local> 'random/random/stateful_normal/StatefulStandardNormalV2', len = 54
      op.type = <local> 'StatefulStandardNormalV2', len = 24
LookupError: No gradient defined for operation 'random/random/stateful_normal/StatefulStandardNormalV2' (op type: StatefulStandardNormalV2)
```

```python
def test_random_normal_train_epoch():
  # https://github.com/rwth-i6/returnn_common/issues/198
  class _Net(nn.Module):
    def __call__(self, x_: nn.Tensor) -> nn.Tensor:
      return x_ + nn.random_normal(x_.shape_ordered)

  from returnn.config import Config
  from returnn.tf.engine import Engine
  from returnn.datasets import init_dataset
  time_dim = nn.SpatialDim("time")
  in_dim = nn.FeatureDim("in", 3)
  x = nn.Data("data", dim_tags=[nn.batch_dim, time_dim, in_dim], available_for_inference=True)

  def _config_get_network(epoch: int, **_kwargs) -> dict:
    # noinspection PyStatementEffect
    epoch  # unused
    nn.reset_default_root_name_ctx()
    net = _Net()
    # net = nn.Linear(out_dim)
    out = net(nn.get_extern_data(x))
    out.mark_as_default_output()
    out.mark_as_loss()
    net_dict = nn.get_returnn_config().get_net_dict_raw_dict(net)
    return net_dict

  config = Config({
    "task": "train", "num_epochs": 1, "start_epoch": 1,
    "get_network": _config_get_network,
    "extern_data": {x.name: {"dim_tags": [nn.batch_dim, time_dim, in_dim], "available_for_inference": True}},
  })
  train_dataset = init_dataset(
    {"class": "DummyDataset", "input_dim": in_dim.dimension, "output_dim": 5, "num_seqs": 3})
  engine = Engine(config)
  engine.init_train_from_config(config, train_data=train_dataset)
  res = engine.train_epoch()
  print(res)
```

**Comment by albertz** [comment]
For this test case, I get a different error:
```Exception: no single variable to train```
Which is actually correct. There is no variable to train in this network.

I wonder why you get this different error? It should not try to use the gradient of `StatefulStandardNormalV2` because the state variable of the random op should not be trained. Is the random state var marked as trainable for you?

What TF version?

**Comment by Atticus1806** [comment]
TF 2.3.0

Yes is marks it as trainable: 
`net trainable params: [<tf.Variable 'random/state_var0/param:0' shape=(3,) dtype=int64>]`

**Comment by albertz** [comment]
I changed the test case to have some trainable variables, and then the tests passes for me:
```
def test_random_normal_train_epoch():
  # https://github.com/rwth-i6/returnn_common/issues/198
  class _Net(nn.Module):
    def __init__(self):
      super(_Net, self).__init__()
      self.linear = nn.Linear(in_dim)

    def __call__(self, x_: nn.Tensor) -> nn.Tensor:
      return self.linear(x_ + nn.random_normal(x_.shape_ordered)) + x_

  from returnn.config import Config
  from returnn.tf.engine import Engine
  from returnn.datasets import init_dataset
  time_dim = nn.SpatialDim("time")
  in_dim = nn.FeatureDim("in", 3)
  x = nn.Data("data", dim_tags=[nn.batch_dim, time_dim, in_dim], available_for_inference=True)

  def _config_get_network(epoch: int, **_kwargs) -> dict:
    # noinspection PyStatementEffect
    epoch  # unused
    nn.reset_default_root_name_ctx()
    net = _Net()
    # net = nn.Linear(out_dim)
    out = net(nn.get_extern_data(x))
    out.mark_as_default_output()
    out.mark_as_loss()
    net_dict = nn.get_returnn_config().get_net_dict_raw_dict(net)
    return net_dict

  config = Config({
    "task": "train", "num_epochs": 1, "start_epoch": 1,
    "get_network": _config_get_network,
    "extern_data": {x.name: {"dim_tags": [nn.batch_dim, time_dim, in_dim], "available_for_inference": True}},
  })
  train_dataset = init_dataset(
    {"class": "DummyDataset", "input_dim": in_dim.dimension, "output_dim": 5, "num_seqs": 3})
  engine = Engine(config)
  engine.init_train_from_config(config, train_data=train_dataset)
  engine.train_epoch()
```

**Comment by Atticus1806** [comment]
This version also crashes with the same error.

**Comment by albertz** [comment]
I now pushed a small change where I explicitly mark the state var as non-trainable. Does that work for you now?

**Comment by Atticus1806** [comment]
Ah didnt see the fix yet, ill check it one sec.

**Comment by Atticus1806** [comment]
Yes works, thanks a lot!
