### ISSUE TITLE
nn.random_normal during forward: must feed size tensor

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn_common#205]
I am currently working on random sampling and while training with a config worked flawlessly, using the config for inference causes problems. I assume this is only happening because during training I am using `declare_same_as` for a loss, but this does not work for forward since I am doing upsampling with lengths the model predicts, so there will be a mismatch if I just put `declare_same_as`  (Error goes away but a different shape mismatch error occurs). But this only for context, now to the problem.

```
TensorFlow exception: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
         [[random/random/stateful_normal/_17]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'extern_data/placeholders/audio_features/audio_features_dim0_size':
  File "u/hilmes/returnn/rnn.py", line 11, in <module>
    main()
  File "u/hilmes/returnn/returnn/__main__.py", line 657, in main
    execute_main_task()
  File "u/hilmes/returnn/returnn/__main__.py", line 489, in execute_main_task
    engine.init_network_from_config(config)
  File "u/hilmes/returnn/returnn/tf/engine.py", line 1121, in init_network_from_config
    self._init_network(net_desc=net_dict, epoch=self.epoch)
  File "u/hilmes/returnn/returnn/tf/engine.py", line 1297, in _init_network
    extern_data.init_from_config(config=self.config, auto_create_placeholders=not use_dataset_pipeline)
  File "u/hilmes/returnn/returnn/tf/network.py", line 68, in init_from_config
    self.data[key] = Data(name=key, auto_create_placeholders=auto_create_placeholders, **init_args)
  File "u/hilmes/returnn/returnn/tf/util/data.py", line 2733, in __init__
    _auto_create_size_placeholders_on_dim_tags(name=name, dim_tags=dim_tags)
  File "u/hilmes/returnn/returnn/tf/util/data.py", line 5790, in _auto_create_size_placeholders_on_dim_tags
    _create_size_placeholder(name=name, axis_wo_b=axis_wo_b, tag=tag, batch_dim=batch_dim_)
  File "u/hilmes/returnn/returnn/tf/util/data.py", line 5651, in _create_size_placeholder
    dyn_size = tf_compat.v1.placeholder(
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 3100, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6808, in placeholder
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

Exception InvalidArgumentError() in step 0. (pid 2438)
Failing op: <tf.Operation 'extern_data/placeholders/audio_features/audio_features_dim0_size' type=Placeholder>
Used by: [<tf.Operation 'extern_data/placeholders/audio_features/batch_dim/Shape' type=Shape>]
  File "/u/hilmes/returnn/rnn.py", line 11, in <module>
    main()                                                                                                                                                                        [201/1980]  File "/u/hilmes/returnn/returnn/__main__.py", line 657, in main
    execute_main_task()
  File "/u/hilmes/returnn/returnn/__main__.py", line 489, in execute_main_task
    engine.init_network_from_config(config)
  File "/u/hilmes/returnn/returnn/tf/engine.py", line 1121, in init_network_from_config
    self._init_network(net_desc=net_dict, epoch=self.epoch)
  File "/u/hilmes/returnn/returnn/tf/engine.py", line 1297, in _init_network
    extern_data.init_from_config(config=self.config, auto_create_placeholders=not use_dataset_pipeline)
  File "/u/hilmes/returnn/returnn/tf/network.py", line 79, in init_from_config
    self.init_batch_info()
  File "/u/hilmes/returnn/returnn/tf/network.py", line 159, in init_batch_info
    batch_dim = get_shape_dim(data.size_placeholder[0], 0, name="batch_dim")
  File "/u/hilmes/returnn/returnn/tf/util/basic.py", line 879, in get_shape_dim
    return tf.shape(x)[axis]
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 601, in shape_v2
    return shape(input, name, out_type)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 628, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 656, in shape_internal
    return gen_array_ops.shape(input, name=name, out_type=out_type)
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 9035, in shape
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

Input to output:
[<tf.Operation 'extern_data/placeholders/audio_features/audio_features_dim0_size' type=Placeholder>,
 <tf.Operation 'extern_data/placeholders/audio_features/batch_dim/Shape' type=Shape>,
 <tf.Operation 'extern_data/placeholders/audio_features/batch_dim/strided_slice' type=StridedSlice>,
 <tf.Operation 'random/random/stateful_normal/shape' type=Pack>,
 <tf.Operation 'random/random/stateful_normal/StatefulStandardNormalV2' type=StatefulStandardNormalV2>,
 <tf.Operation 'random/random/stateful_normal/mul' type=Mul>,
 <tf.Operation 'random/random/stateful_normal' type=Add>]
Step meta information:
{'seq_idx': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 'seq_tag': ['train-clean-100/7859-102521-0000/7859-102521-0000',
             'train-clean-100/3259-158083-0039/3259-158083-0039',
             'train-clean-100/1183-128659-0018/1183-128659-0018',
             'train-clean-100/8063-274117-0028/8063-274117-0028',
             'train-clean-100/7278-91083-0002/7278-91083-0002',
             'train-clean-100/2843-152918-0005/2843-152918-0005',
             'train-clean-100/1926-147979-0049/1926-147979-0049',
             'train-clean-100/4195-17507-0023/4195-17507-0023',
             'train-clean-100/1447-130550-0021/1447-130550-0021',
             'train-clean-100/4680-16042-0027/4680-16042-0027',
             'train-clean-100/5022-29411-0018/5022-29411-0018',
             'train-clean-100/2002-139469-0115/2002-139469-0115',
             'train-clean-100/3436-172162-0052/3436-172162-0052',
             'train-clean-100/8975-270782-0114/8975-270782-0114',
             'train-clean-100/3242-8112-0009/3242-8112-0009',
             'train-clean-100/1455-138263-0002/1455-138263-0002']}
Feed dict:
  <tf.Tensor 'extern_data/placeholders/phonemes/phonemes:0' shape=(?, ?) dtype=int32>: shape (16, 51), dtype int32, min/max 0/42, Data{'phonemes', [B,T|'phonemes_time'[B]], dtype='int32', sparse_dim=Dim{F'phonemes_indices'(44)}}
  <tf.Tensor 'extern_data/placeholders/phonemes/phonemes_dim0_size:0' shape=(?,) dtype=int32>: shape (16,), dtype int32, min/max 18/51, ([18 24 27 26 39 34 32 41 29 35 38 27 46 46 51 40])
  <tf.Tensor 'extern_data/placeholders/seq_tag/seq_tag:0' shape=(?,) dtype=string>: type <class 'list'>, Data{'seq_tag', [B?], dtype='string'}
EXCEPTION
Traceback (most recent call last):
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1365, in BaseSession._do_call
    line: return fn(*args)
    locals:
      fn = <local> <function BaseSession._do_run.<locals>._run_fn at 0x7f9116435af0>
      args = <local> ({<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f915728cdf0>: array([[42, 41,  9,  2, 41,  5, 19,  2, 22,  2, 19, 20,  1, 28, 30, 28,
                             41, 40,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                              0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                         ...
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1349, in BaseSession._do_run.<locals>._run_fn
    line: return self._call_tf_sessionrun(options, feed_dict, fetch_list,
                                          target_list, run_metadata)
    locals:
      self = <local> <tensorflow.python.client.session.Session object at 0x7f9154d74b20>
      self._call_tf_sessionrun = <local> <bound method BaseSession._call_tf_sessionrun of <tensorflow.python.client.session.Session object at 0x7f9154d74b20>>
      options = <local> None
      feed_dict = <local> {<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f915728cdf0>: array([[42, 41,  9,  2, 41,  5, 19,  2, 22,  2, 19, 20,  1, 28, 30, 28,
                                  41, 40,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                                   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                               ...
      fetch_list = <local> [<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f91573a3b30>]
      target_list = <local> []
      run_metadata = <local> None
  File "/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1441, in BaseSession._call_tf_sessionrun
    line: return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
                                                  fetch_list, target_list,
                                                  run_metadata)
    locals:
      tf_session = <global> <module 'tensorflow.python.client.pywrap_tf_session' from '/work/asr3/rossenbach/hilmes/librosa_tf/lib/python3.8/site-packages/tensorflow/python/client/pywrap_tf_session.py'>
      tf_session.TF_SessionRun_wrapper = <global> <built-in method TF_SessionRun_wrapper of PyCapsule object at 0x7f923b7c5cf0>
      self = <local> <tensorflow.python.client.session.Session object at 0x7f9154d74b20>
      self._session = <local> <tensorflow.python._pywrap_tf_session.TF_Session object at 0x7f91574c47b0>
      options = <local> None
      feed_dict = <local> {<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f915728cdf0>: array([[42, 41,  9,  2, 41,  5, 19,  2, 22,  2, 19, 20,  1, 28, 30, 28,
                                  41, 40,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                                   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                               ...
      fetch_list = <local> [<tensorflow.python._pywrap_tf_session.TF_Output object at 0x7f91573a3b30>]
      target_list = <local> []
      run_metadata = <local> None
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[{{node extern_data/placeholders/audio_features/audio_features_dim0_size}}]]
         [[random/random/stateful_normal/_17]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[{{node extern_data/placeholders/audio_features/audio_features_dim0_size}}]]
0 successful operations.
0 derived errors ignored.
```

Then there is a similar exception below which ends with: 
```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
         [[random/random/stateful_normal/_17]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'extern_data/placeholders/audio_features/audio_features_dim0_size' with dtype int32 and shape [?]
         [[node extern_data/placeholders/audio_features/audio_features_dim0_size (defined at u/hilmes/returnn/returnn/tf/util/data.py:5651) ]]
0 successful operations.
0 derived errors ignored.
```

I was able to shrink down the network and the confusing part is: Even when removing the part that relies on the size tensor (e.g. upsampling etc.) the error persists as long as `nn.random_normal` is in the network.
The smallest net I was able to reproduce the error with was:
```
class NARTTSModel(nn.Module):
  def __init__(self):
    super(NARTTSModel, self).__init__()
    vae_lin_dim = nn.FeatureDim("vae_embedding", 512)
    self.vae_embedding = nn.Linear(vae_lin_dim)

  def __call__(self, text: nn.Tensor):
    vae_embedding = self.vae_embedding(text)
    rand = nn.random_normal(vae_embedding.shape_ordered)
    return rand
```
When removing the `random_normal` part this works.

A gist with the shrinked returnn config is here: [returnn.config](https://gist.github.com/Atticus1806/5cc9ff3e7bc32666af2be34e025e7d9d)

**Comment by Atticus1806** [comment]
I am currently also trying to produce a test case, but right now this does _not_ crash yet (so I am doing something wrong when replicating), my attempt was smth. like: 

```python
def test_random_normal_forward():
  class _Net(nn.Module):
    def __init__(self):
      super(_Net, self).__init__()
      self.linear = nn.Linear(in_dim)

    def __call__(self, x_: nn.Tensor, second: nn.Tensor) -> nn.Tensor:
      lin = self.linear(x_)
      return nn.random_normal(lin.shape_ordered)

  from returnn.config import Config
  from returnn.tf.engine import Engine
  from returnn.datasets import init_dataset
  time_dim = nn.SpatialDim("time")
  time_dim2 = nn.SpatialDim("time2")
  in_dim = nn.FeatureDim("in", 3)
  x = nn.Data("data", dim_tags=[nn.batch_dim, time_dim, in_dim], available_for_inference=True)
  y = nn.Data("classes", dim_tags=[nn.batch_dim, time_dim2, in_dim], available_for_inference=True)

  def _config_get_network(epoch: int, **_kwargs) -> dict:
    # noinspection PyStatementEffect
    epoch  # unused
    nn.reset_default_root_name_ctx()
    net = _Net()
    # net = nn.Linear(out_dim)
    out = net(nn.get_extern_data(x), nn.get_extern_data(y))
    out.mark_as_default_output()
    out.mark_as_loss()
    net_dict = nn.get_returnn_config().get_net_dict_raw_dict(net)
    return net_dict

  config = Config({
    #"task": "train",
    "allow_random_model_init": True,
    "get_network": _config_get_network,
    "extern_data": {x.name: {"dim_tags": [nn.batch_dim, time_dim, in_dim], "available_for_inference": True},
                    y.name: {"dim_tags": [nn.batch_dim, time_dim2, in_dim], "available_for_inference": True}},
  })
  train_dataset = init_dataset({
    "class": "DummyDatasetMultipleDataKeys",
    "output_dim": {"data": 3, "classes": 3}, "num_seqs": 3})
  engine = Engine(config)
  engine.init_train_from_config(config, train_data=train_dataset)
  engine.forward_single(train_dataset, seq_idx=0)
```

**Comment by albertz** [comment]
From the error alone, it looks related to https://github.com/rwth-i6/returnn/issues/1102 ?

**Comment by albertz** [comment]
In any case, the problem probably is about whatever you do with `declare_same_as`? But I don't see that in the test?

Btw, keep the test simple. Do not use such `get_network` when not really needed.

**Comment by albertz** [comment]
Can you also post the raw net dict? (This is often more helpful for debugging.)

**Comment by Atticus1806** [comment]
> From the error alone, it looks related to https://github.com/rwth-i6/returnn/issues/1102 ?

Ah yes, this is possible.

> In any case, the problem probably is about whatever you do with `declare_same_as`?

I am not sure. During testing I found that using `declare_same_as` (at a different part of the network where it "made sense") was able to fix this but cause other problems. But the error occurs without it, thats why its not in here. 

```python
{'output': {'class': 'copy', 'from': 'random', 'out_shape': {Dim{'phonemes_time'[B(-1)]}, Dim{B}, Dim{F'vae_embedding'(512)}}},
 'random': {'class': 'subnetwork', 'from': [], 
            'subnetwork': {'random_state_init': {'class': 'random_state_init', 'out_dim': Dim{F'random-state'(3)}, 'out_shape': {Dim{F'random-state'(3)}}}, 
                           'random': {'class': 'random', 'shape': (Dim{B}, Dim{'phonemes_time'[B(-1)]}, Dim{F'vae_embedding'(512)}), 'distribution': 'normal', 'mean': 0.0, 'stddev': 1.0, 'explicit_state': 'state_var0', 'auto_update_state': True, 'shape_deps': ['base:data:phonemes']}, 
                           'output': {'class': 'copy', 'from': 'random', 'out_shape': {Dim{'phonemes_time'[B(-1)]}, Dim{B}, Dim{F'vae_embedding'(512)}}}, 
                           'state_var0': {'class': 'variable', 'shape': [Dim{F'random-state'(3)}], 'param_name': 'param', 'dtype': 'int64', 'trainable': False, 'init_by_layer': 'random_state_init'}}, 'out_shape': {Dim{'phonemes_time'[B(-1)]}, Dim{B}, Dim{F'vae_embedding'(512)}}}}
```

**Comment by Atticus1806** [comment]
> Btw, keep the test simple. Do not use such get_network when not really needed.

Agreed. You are right. I removed the `returnn_common` and `get_network` part and moving this to the RETURNN git then. 
But I am not really sure how to further investigate this. Somehow the information of the extern data is not set properly? I am confident it is somehow related to random, since e.g. just using a copy layer (or as of the previous returnn_common example with the linear layer from this checkpoint) does not crash.

[returnn.config](https://gist.github.com/Atticus1806/8b97357ab0ad303cc9ddca7771d5ecf1)
